PainlessPrep-CapstoneSpring2025: com.example.uitest.databinding.TakepicturepageBinding Class Reference
com.example.uitest.databinding.TakepicturepageBinding Class Reference
Public Member Functions
ConstraintLayout getRoot ()
Static Public Member Functions
static TakepicturepageBinding inflate (@NonNull LayoutInflater inflater)
static TakepicturepageBinding inflate (@NonNull LayoutInflater inflater, @Nullable ViewGroup parent, boolean attachToParent)
static TakepicturepageBinding bind (@NonNull View rootView)
Public Attributes
final Button imageCaptureButton
final Button index
final PreviewView viewFinder
Member Function Documentation
bind()
static TakepicturepageBinding com.example.uitest.databinding.TakepicturepageBinding.bind (@NonNull View rootView) static
References imageCaptureButton, index, and viewFinder.
Referenced by inflate().
getRoot()
ConstraintLayout com.example.uitest.databinding.TakepicturepageBinding.getRoot ()
inflate() [1/2]
static TakepicturepageBinding com.example.uitest.databinding.TakepicturepageBinding.inflate (@NonNull LayoutInflater inflater) static
References inflate().
Referenced by inflate(), and inflate().
inflate() [2/2]
static TakepicturepageBinding com.example.uitest.databinding.TakepicturepageBinding.inflate (@NonNull LayoutInflater inflater, @Nullable ViewGroup parent, boolean attachToParent) static
References bind(), and inflate().
Member Data Documentation
imageCaptureButton
final Button com.example.uitest.databinding.TakepicturepageBinding.imageCaptureButton
Referenced by bind().
index
final Button com.example.uitest.databinding.TakepicturepageBinding.index
Referenced by bind().
viewFinder
final PreviewView com.example.uitest.databinding.TakepicturepageBinding.viewFinder
Referenced by bind().
The documentation for this class was generated from the following file:
C:/Users/Jerron/Documents/UNO Classes/SP25/Capstone/code/OurImplmentation/Painful-Prep/front-end/UITest/app/build/generated/data_binding_base_class_source_out/debug/out/com/example/uitest/databinding/TakepicturepageBinding.java