PainfulPrep: com.example.uitest.databinding.ResultsBinding Class Reference
com.example.uitest.databinding.ResultsBinding Class Reference
Public Member Functions
ConstraintLayout getRoot ()
Static Public Member Functions
static ResultsBinding inflate (@NonNull LayoutInflater inflater)
static ResultsBinding inflate (@NonNull LayoutInflater inflater, @Nullable ViewGroup parent, boolean attachToParent)
static ResultsBinding bind (@NonNull View rootView)
Public Attributes
final TextView dimensionsView
final ImageView imageView
final Button index
Member Function Documentation
bind()
static ResultsBinding com.example.uitest.databinding.ResultsBinding.bind (@NonNull View rootView) static
References dimensionsView, imageView, and index.
Referenced by inflate().
getRoot()
ConstraintLayout com.example.uitest.databinding.ResultsBinding.getRoot ()
inflate() [1/2]
static ResultsBinding com.example.uitest.databinding.ResultsBinding.inflate (@NonNull LayoutInflater inflater) static
References inflate().
Referenced by inflate(), and inflate().
inflate() [2/2]
static ResultsBinding com.example.uitest.databinding.ResultsBinding.inflate (@NonNull LayoutInflater inflater, @Nullable ViewGroup parent, boolean attachToParent) static
References bind(), and inflate().
Member Data Documentation
dimensionsView
final TextView com.example.uitest.databinding.ResultsBinding.dimensionsView
Referenced by bind().
imageView
final ImageView com.example.uitest.databinding.ResultsBinding.imageView
Referenced by bind().
index
final Button com.example.uitest.databinding.ResultsBinding.index
Referenced by bind().
The documentation for this class was generated from the following file:
C:/Users/Jerron/Documents/UNO Classes/SP25/Capstone/code/OurImplmentation/Painful-Prep/front-end/UITest/app/build/generated/data_binding_base_class_source_out/debug/out/com/example/uitest/databinding/ResultsBinding.java