PainfulPrep: com.example.uitest.databinding.IndexBinding Class Reference
com.example.uitest.databinding.IndexBinding Class Reference
Public Member Functions
ConstraintLayout getRoot ()
Static Public Member Functions
static IndexBinding inflate (@NonNull LayoutInflater inflater)
static IndexBinding inflate (@NonNull LayoutInflater inflater, @Nullable ViewGroup parent, boolean attachToParent)
static IndexBinding bind (@NonNull View rootView)
Public Attributes
final Button TakePicture
final EditText ip
final Button uploadPicture
Member Function Documentation
bind()
static IndexBinding com.example.uitest.databinding.IndexBinding.bind (@NonNull View rootView) static
References ip, TakePicture, and uploadPicture.
Referenced by inflate().
getRoot()
ConstraintLayout com.example.uitest.databinding.IndexBinding.getRoot ()
inflate() [1/2]
static IndexBinding com.example.uitest.databinding.IndexBinding.inflate (@NonNull LayoutInflater inflater) static
References inflate().
Referenced by inflate(), and inflate().
inflate() [2/2]
static IndexBinding com.example.uitest.databinding.IndexBinding.inflate (@NonNull LayoutInflater inflater, @Nullable ViewGroup parent, boolean attachToParent) static
References bind(), and inflate().
Member Data Documentation
ip
final EditText com.example.uitest.databinding.IndexBinding.ip
Referenced by bind().
TakePicture
final Button com.example.uitest.databinding.IndexBinding.TakePicture
Referenced by bind().
uploadPicture
final Button com.example.uitest.databinding.IndexBinding.uploadPicture
Referenced by bind().
The documentation for this class was generated from the following file:
C:/Users/Jerron/Documents/UNO Classes/SP25/Capstone/code/OurImplmentation/Painful-Prep/front-end/UITest/app/build/generated/data_binding_base_class_source_out/debug/out/com/example/uitest/databinding/IndexBinding.java