PainlessPrep-CapstoneSpring2025: com.example.uitest.databinding.ImportpicturepageBinding Class Reference
com.example.uitest.databinding.ImportpicturepageBinding Class Reference
Public Member Functions
ConstraintLayout getRoot ()
Static Public Member Functions
static ImportpicturepageBinding inflate (@NonNull LayoutInflater inflater)
static ImportpicturepageBinding inflate (@NonNull LayoutInflater inflater, @Nullable ViewGroup parent, boolean attachToParent)
static ImportpicturepageBinding bind (@NonNull View rootView)
Public Attributes
final Button index
final Button uploadPicture
Member Function Documentation
bind()
static ImportpicturepageBinding com.example.uitest.databinding.ImportpicturepageBinding.bind (@NonNull View rootView) static
References index, and uploadPicture.
Referenced by inflate().
getRoot()
ConstraintLayout com.example.uitest.databinding.ImportpicturepageBinding.getRoot ()
inflate() [1/2]
static ImportpicturepageBinding com.example.uitest.databinding.ImportpicturepageBinding.inflate (@NonNull LayoutInflater inflater) static
References inflate().
Referenced by inflate(), and inflate().
inflate() [2/2]
static ImportpicturepageBinding com.example.uitest.databinding.ImportpicturepageBinding.inflate (@NonNull LayoutInflater inflater, @Nullable ViewGroup parent, boolean attachToParent) static
References bind(), and inflate().
Member Data Documentation
index
final Button com.example.uitest.databinding.ImportpicturepageBinding.index
Referenced by bind().
uploadPicture
final Button com.example.uitest.databinding.ImportpicturepageBinding.uploadPicture
Referenced by bind().
The documentation for this class was generated from the following file:
C:/Users/Jerron/Documents/UNO Classes/SP25/Capstone/code/OurImplmentation/Painful-Prep/front-end/UITest/app/build/generated/data_binding_base_class_source_out/debug/out/com/example/uitest/databinding/ImportpicturepageBinding.java