PainfulPrep: one_marker_detect_v2 Namespace Reference
one_marker_detect_v2 Namespace Reference
Functions
np.ndarray apply_dog (np.ndarray image, sigma1=1.0, sigma2=2.0)
apply_canny (np.ndarray image)
np.ndarray find_windowpane (Path path)
tuple get_window_dimensions (str path, np.ndarray quadrilateral)
Variables
int MARKER_LENGTH_MM = 100
float MM_IN_RATIO = 25.4
bool OUTPUT_PASSES = False
np.ndarray windowpane = find_windowpane(sys.argv[1])
width
height
Detailed Description
@file one_marker_detect_v2.py
@brief Uses an updated pipeline to get dimensions for window in picture file.
Usage: python one_marker_detect_v2.py <file_path>
Function Documentation
apply_canny()
one_marker_detect_v2.apply_canny (np.ndarray image)
@brief Applies Canny edge detection.
@param image The image to process.
@return The processed image.
Referenced by find_windowpane().
apply_dog()
np.ndarray one_marker_detect_v2.apply_dog (np.ndarray image, sigma1 = 1.0, sigma2 = 2.0)
@brief Applies Difference of Gaussians edge detection.
@param image The image to process.
@param sigma1 The value of the first Gaussian blur.
@param sigma2 The value of the second Gaussian blur.
@return The processed image.
Referenced by find_windowpane().
find_windowpane()
np.ndarray one_marker_detect_v2.find_windowpane (Path path)
@brief Finds the window in an image.
@param path File path to picture containing the window.
@return Coordinates of corners of the detected window as a numpy.ndarray.
References apply_canny(), apply_dog(), and line_finder.process_lines().
Referenced by test_marker_detectors.run_demo_tool_v2().
get_window_dimensions()
tuple one_marker_detect_v2.get_window_dimensions (str path, np.ndarray quadrilateral)
@brief Computes the width and height of a detected window.
@param path File path to the image containing the window.
@param quadrilateral Coordinates of the detected window corners.
@return Tuple containing the width and height of the window in inches.
Referenced by test_marker_detectors.run_demo_tool_v2().
Variable Documentation
height
one_marker_detect_v2.height
MARKER_LENGTH_MM
int one_marker_detect_v2.MARKER_LENGTH_MM = 100
MM_IN_RATIO
float one_marker_detect_v2.MM_IN_RATIO = 25.4
OUTPUT_PASSES
bool one_marker_detect_v2.OUTPUT_PASSES = False
width
one_marker_detect_v2.width
windowpane
np.ndarray one_marker_detect_v2.windowpane = find_windowpane(sys.argv[1])