PainlessPrep-CapstoneSpring2025: manual_measurement Namespace Reference
manual_measurement Namespace Reference
Functions
main ()
click_handler (event, x, y, _, tuple[list, list] params)
np.ndarray resize_with_aspect_ratio (np.ndarray image, int width=None, int height=None)
Detailed Description
@file manual_measurement.py
@brief Manually select corners of window and markers to compute dimensions.
This tool allows for manually selecting the corners of a window for dimension calculation.
Usage:
    python manual_measurement.py <filepath> <marker_size>
@note The marker size must be provided in millimeters (mm).
Function Documentation
click_handler()
manual_measurement.click_handler (event, x, y, _, tuple[list, list] params)
Mouse click event handler. Only reacts to left mouse clicks.
main()
manual_measurement.main ()
References two_marker_detect.get_diff_two_markers_px(), two_marker_detect.get_scale(), and resize_with_aspect_ratio().
Referenced by resize_with_aspect_ratio().
resize_with_aspect_ratio()
np.ndarray manual_measurement.resize_with_aspect_ratio (np.ndarray image, int width = None, int height = None)
References main().
Referenced by main().