PainlessPrep-CapstoneSpring2025: line_finder Namespace Reference
line_finder Namespace Reference
Functions
line_length (line)
line_angle (line)
filter_lines_by_angle (lines, angle_ref, tolerance=5)
point_line_distance (point, line_pt1, line_pt2)
line_intersection (line1, line2)
get_four_intersections (intersections, image_shape)
get_intersections (lines)
fit_quadrilateral (intersections)
line_midpoint (l)
angular_distance (a, b)
average_line_midpoint (lines, length_thresh=100)
select_window_edges (lines, image, length_thresh=100, angle_tolerance=45)
process_lines (combined_image, show_output=False)
show_lines (lines, image, intersections=None, quad=None)
Detailed Description
@file line_finder.py
@brief Takes provides the function process_lines for finding a quadrilateral from a processed image.
Function Documentation
angular_distance()
line_finder.angular_distance (a, b)
Returns the shortest distance between two angles (degrees, 0–180)
Referenced by select_window_edges().
average_line_midpoint()
line_finder.average_line_midpoint (lines, length_thresh = 100)
References line_midpoint().
Referenced by process_lines(), and select_window_edges().
filter_lines_by_angle()
line_finder.filter_lines_by_angle (lines, angle_ref, tolerance = 5)
@brief Keep lines that are within tolerance
@param lines lines to iterate over
@param angle_ref reference angle
@param tolerance tolerance in degrees
@return filtered lines
References line_angle().
Referenced by process_lines().
fit_quadrilateral()
line_finder.fit_quadrilateral (intersections)
@brief Attempts to fit a 4-point quadrilateral from the given intersection points.
@param intersections list of four intersection points
@return quadrilateral
Referenced by process_lines().
get_four_intersections()
line_finder.get_four_intersections (intersections, image_shape)
@brief Selects four intersection points from a list of intersections, one for each corner.
@param intersections list of potential intersection points
@param image_shape dimensions of the image
@return list of four intersection points
Referenced by process_lines().
get_intersections()
line_finder.get_intersections (lines)
Find intersections for each pair of lines (if they intersect within image bounds).
References line_intersection().
Referenced by process_lines().
line_angle()
line_finder.line_angle (line)
Return angle in degrees (0-180) of a line defined by [x1,y1,x2,y2] or [[x1,y1,x2,y2]].
Referenced by filter_lines_by_angle(), process_lines(), and select_window_edges().
line_intersection()
line_finder.line_intersection (line1, line2)
@brief Returns the intersection point of two lines
 @param line1 First line defined as [x1,y1,x2,y2] or [[x1,y1,x2,y2]]
 @param line2 Second line defined as [x1,y1,x2,y2] or [[x1,y1,x2,y2]]
 @return intersection point
Referenced by get_intersections().
line_length()
line_finder.line_length (line)
Compute Euclidean length of a line given as [x1,y1,x2,y2].
line_midpoint()
line_finder.line_midpoint (l)
Referenced by average_line_midpoint(), and select_window_edges().
point_line_distance()
line_finder.point_line_distance (point, line_pt1, line_pt2)
Compute the distance from a point to a line (defined by two points).
process_lines()
line_finder.process_lines (combined_image, show_output = False)
@brief Takes a processed image of a window and returns lines of its edges
@param combined_image processed image of window
@param show_output show output of each pass in a seperate window
@return list of 4 lines
References average_line_midpoint(), filter_lines_by_angle(), fit_quadrilateral(), get_four_intersections(), get_intersections(), line_angle(), select_window_edges(), and show_lines().
Referenced by one_marker_detect_v2.find_windowpane().
select_window_edges()
line_finder.select_window_edges (lines, image, length_thresh = 100, angle_tolerance = 45)
@brief Selects window edges around the given image.
@param lines list of potential edges as lines
@param image image
@param length_thresh threshold length for finding midpoint
@param angle_tolerance angle tolerance for selecting window edges
@return list of 4 lines
References angular_distance(), average_line_midpoint(), line_angle(), and line_midpoint().
Referenced by process_lines().
show_lines()
line_finder.show_lines (lines, image, intersections = None, quad = None)
Displays lines, points, and/or a quad on the given image in a new window.
Referenced by process_lines().