PainlessPrep-CapstoneSpring2025: test_marker_detectors Namespace Reference
test_marker_detectors Namespace Reference
Functions
run_demo_tool ()
run_two_marker_detect ()
run_demo_tool_v2 ()
report_best_and_worst_results (results)
save_results (filename, data)
Variables
str test_images = "test-images"
str data_csv = "test-images/data.csv"
str results_csv = "test-images/results.csv"
dict expected_data = {}
newline
reader = csv.DictReader(csvfile)
list results = []
list accuracy_scores = []
list one_marker_accuracies = []
list two_marker_accuracies = []
list one_marker_v2_accuracies = []
int one_marker_attempts = 0
int two_marker_attempts = 0
int one_marker_v2_attempts = 0
int one_marker_success = 0
int two_marker_success = 0
int one_marker_v2_success = 0
Function Documentation
report_best_and_worst_results()
test_marker_detectors.report_best_and_worst_results (results)
Report the best case (image with the smallest absolute sum of diff_width and diff_height)
and the worst case (image with the largest absolute sum of diff_width and diff_height)
Referenced by save_results().
run_demo_tool()
test_marker_detectors.run_demo_tool ()
Run the one marker detection demo tool on all images with one marker and a false ignore flag in data.csv
References one_marker_detect.find_windowpane(), and one_marker_detect.get_window_dimensions().
Referenced by save_results().
run_demo_tool_v2()
test_marker_detectors.run_demo_tool_v2 ()
Run the one marker detection v2 on all images with one marker and a false ignore flag in data.csv
References one_marker_detect_v2.find_windowpane(), and one_marker_detect_v2.get_window_dimensions().
Referenced by save_results().
run_two_marker_detect()
test_marker_detectors.run_two_marker_detect ()
Run the two marker detection on all images with two markers and a false ignore flag in data.csv
This function also separates which marker type is used in the image.
References two_marker_detect.calculate_two_markers().
Referenced by save_results().
save_results()
test_marker_detectors.save_results (filename, data)
Save the results to a CSV file
References report_best_and_worst_results(), run_demo_tool(), run_demo_tool_v2(), run_two_marker_detect(), and save_results().
Referenced by save_results().
Variable Documentation
accuracy_scores
list test_marker_detectors.accuracy_scores = []
data_csv
test_marker_detectors.data_csv = "test-images/data.csv"
expected_data
dict test_marker_detectors.expected_data = {}
newline
test_marker_detectors.newline
one_marker_accuracies
list test_marker_detectors.one_marker_accuracies = []
one_marker_attempts
int test_marker_detectors.one_marker_attempts = 0
one_marker_success
int test_marker_detectors.one_marker_success = 0
one_marker_v2_accuracies
list test_marker_detectors.one_marker_v2_accuracies = []
one_marker_v2_attempts
int test_marker_detectors.one_marker_v2_attempts = 0
one_marker_v2_success
int test_marker_detectors.one_marker_v2_success = 0
reader
test_marker_detectors.reader = csv.DictReader(csvfile)
results
list test_marker_detectors.results = []
results_csv
str test_marker_detectors.results_csv = "test-images/results.csv"
test_images
str test_marker_detectors.test_images = "test-images"
two_marker_accuracies
list test_marker_detectors.two_marker_accuracies = []
two_marker_attempts
int test_marker_detectors.two_marker_attempts = 0
two_marker_success
int test_marker_detectors.two_marker_success = 0