PainlessPrep-CapstoneSpring2025: two_marker_detect Namespace Reference
two_marker_detect Namespace Reference
Functions
tuple[int, int] calculate_two_markers (Path path, int marker_size_mm, Literal["ArUco", "AprilTag"] marker_type="ArUco", float border_offset_in=0)
float get_scale (np.ndarray corners)
tuple[int, int, int, int] get_diff_two_markers_px (list[tuple[int, int]] coords, Literal["TLBR", "TRBL"] diagonal="TLBR")
Variables
width
height
Detailed Description
@file two_marker_detect.py
@brief Gets dimensions of a window in an image containing two markers in opposing corners.
This script detects two ArUco markers in an image and calculates the width and height
of a window using the known size of the markers.
Usage:
    python two_marker_detect.py <filepath> <marker_size>
@note The marker size must be provided in millimeters (mm).
Function Documentation
calculate_two_markers()
tuple[int, int] two_marker_detect.calculate_two_markers (Path path, int marker_size_mm, Literal["ArUco", "AprilTag"] marker_type = "ArUco", float border_offset_in = 0)
@brief Finds the width and height of a window using two ArUco markers.
This function detects exactly two ArUco markers in an image, computes the scale
based on their known size, and calculates the dimensions of the window in inches.
Calculation involves find the farthest apart marker corners, and then obtaining
the x and y pixel offset. A pixel scale of the markers is used to determine the
real life size difference in inches. Due to camera distortion and suboptimal
camera angles, the final computed dimension is rounded up to the nearest half
inch.
@param path Path to the image file.
@param marker_size_mm Known size of the marker in millimeters.
@param marker_type Defines the specific markers in the image. Has to be a literal
       value either "ArUco" or "AprilTag". Defaults to ArUco markers.
@param border_offset_in Defines the size of the white border around the marker itself.
       White borders help in improving detection of markers and the border size is
       used for calculating the dimensions of the window. Defaults to 0. Border size
       has to be provided in inches.
@return Tuple (width, height) of the window in inches. Returns None if the number
        of markers detected is not exactly two.
References get_diff_two_markers_px(), and get_scale().
Referenced by test_marker_detectors.run_two_marker_detect().
get_diff_two_markers_px()
tuple[int, int, int, int] two_marker_detect.get_diff_two_markers_px (list[tuple[int, int]] coords, Literal["TLBR", "TRBL"] diagonal = "TLBR")
@brief Finds the coordinates of the diagonal of a window.
This function figures out the x and y coordinates of the two opposing corners of a window
based on the placement of the two ArUco markers in those corners.
@param coords List of coordinate pairs in order x, y
@param diagonal Literal that indicates marker placement. TLBR indicates that one marker was
       placed in the top left corner of the window and the other in the bottom right. TRBL
       indicates that one marker was placed in the top right corner and the other in the
       bottom left corner.
@return Returns a four-tuple of integer values. The values are returned in this order:
        Top x coordinate, top y coordinate, bottom x coordinate, bottom y coordinate.
Referenced by two_marker_classes.TwoMarkerDetector.calculate(), calculate_two_markers(), manual_measurement.main(), and test_two_marker_detect.test_get_diff_two_markers_px().
get_scale()
float two_marker_detect.get_scale (np.ndarray corners)
@brief Computes the pixel scale from an ArUco marker.
Given the four corners of a detected marker, this function calculates the
average length of its sides, which is used to determine the scale.
@param corners A 4x2 NumPy array containing the corner coordinates of a marker.
@return The average pixel length of the marker's sides.
Referenced by calculate_two_markers(), two_marker_classes.TwoMarkerDetector.get_scale(), manual_measurement.main(), and test_two_marker_detect.test_get_scale().
Variable Documentation
height
two_marker_detect.height
width
two_marker_detect.width